[project]
api_url = "http://localhost:54321"
studio_url = "http://localhost:54323"
db_url = "postgresql://postgres:<DB_PASSWORD_REDACTED>@localhost:54322/postgres"

[api]
port = 54321
schemas = ["public"]
extra_search_path = ["public"]
max_rows = 1000

[db]
port = 54322
major_version = 14

[studio]
port = 54323

[auth]
enabled = true
site_url = "https://myroofgenius-live.vercel.app"
additional_redirect_urls = ["https://myroofgenius-live.vercel.app/"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
secure_password_change = false
max_frequency = "1m0s"
otp_length = 6
otp_expiry = 86400

[auth.mfa]
max_enrolled_factors = 10

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.mfa.phone]
enroll_enabled = false
verify_enabled = false

[auth.email.template]

[auth.sms]
enable_signup = false
